name: Terraform CI/CD Pipeline

on:
  push:
    branches:
      - '**'  # Trigger on push to any branch
  # pull_request:
  #   types: [synchronize]  # Trigger on pull request updates

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Allow GitHub Actions to request an ID token

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Configure AWS Credentials
      id: aws-credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ secrets.AWS_REGION }}  # AWS region from secrets or define directly
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}  # ARN of the role to assume
        role-session-name: TerraformSession
        audience: sts.amazonaws.com


    - name: Verify AWS Credentials
      run: aws sts get-caller-identity

    # Continue with Terraform commands
    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve
