name: Terraform CI/CD Pipeline

on:
  pull_request:
    paths:
      - 'terraform/**'
    types: [opened, synchronize, reopened]
jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Allow GitHub Actions to request an ID token

    steps:
    # Step 1: Checkout Repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Set up Terraform
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    # Step 3: Configure AWS Credentials
    - name: Configure AWS Credentials
      id: aws-credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ Secrets.AWS_REGION }}   # AWS region from secrets
        role-to-assume: ${{Secrets.ROLE_TO_ASSUME }}
        role-session-name: TerraformSession
        audience: sts.amazonaws.com

    # Step 4: Verify AWS Credentials
    - name: Verify AWS Credentials
      run: aws sts get-caller-identity

    # Step 5: Initialize Terraform
    - name: Terraform Init
      run: terraform init
      working-directory: terraform

    # Step 6: Apply Terraform Changes
    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: terraform
