name: Terraform CI/CD Pipeline

on:
  push:
    branches:
      - '**'  # Trigger on push to any branch
  # pull_request:
  #   types: [synchronize]  # Trigger on pull request updates

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-2  # or use GitHub Secrets
          role-to-assume: arn:aws:iam::692859915147:role/sundeep  # Replace with your role ARN
          role-session-name: TerraformSession
          audience: sts.amazonaws.com

      - name: Change Directory to Terraform
        run: cd terraform  # Navigate to the terraform folder where your .tf files are

      - name: Terraform Init
        run: terraform init
        working-directory: terraform  # Ensure init is run in the correct directory

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: terraform  # Ensure apply is run in the correct directory

